### PR TITLE
Buffer Factory: Add configurability of BufferFactory. 

### PR DESCRIPTION
**Pull request by KBaichoo**
We can now set the minimum account size to track. This will be a PR against upstream once the  [dependent PR](https://github.com/envoyproxy/envoy/pull/17093) it builds upon is merged. 

Signed-off-by: Kevin Baichoo <kbaichoo@google.com>

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes: 
Release Notes: TODO
Platform Specific Features:

### CODE REVIEW

**Comment by KBaichoo** [comment]
This builds on top of https://github.com/envoyproxy/envoy/pull/17093. Since that's not yet merged I can't make an upstream PR on this, yet. Any initial feedback on this @antoniovicente

**Comment by antoniovicente** [comment]
envoyproxy#17093 is nearing merge.  I recommend you look into some other things like implementation of accounts for H1 and H3 while this PR is blocked on review.

**Comment by KBaichoo** [comment]
I'm finishing up tests for the final PR which will include the Overload Manager leveraging this mechanisms fully for H2

**Comment by antoniovicente** [comment]
That sounds great.

**Comment by KBaichoo** [comment]
Closing this, made upstream PR: https://github.com/envoyproxy/envoy/pull/17562

**Pull request closed without merging**
